name: Triggers
run-name: Test triggers

on:
  push:
    branches:
    -  main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje Favorito'
        default: Python
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
        nombre:
          description: 'First Name'
          required: true
          default: Yonalby
          type: string
  schedule:
    - cron: '15 22 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir nombre
        run: echo "USERNAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: Definir lenguaje
        run: echo "LANGUAJE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_lenguaje.py
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu_latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        uses: echo "USERNAME=${{ github.actor }}" >> $GUTHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
  

          
  
